added wordtokenizer
adambarla/NMT-augment pull request #27
Opened 2024-04-03 15:28 UTC by DecayingSeart

Wordtokenizer added. Still open for test before merging.

2024-04-03 15:42 UTC, adambarla requested changes

2024-04-03 15:42 UTC, adambarla commented on src/conf/main.yaml
this represents the default. please revert the changes so character stays as the default

2024-04-04 13:23 UTC, DecayingSeart commented
Now it can be run properly (I'm waiting for its results). Vocab size is now 10000 (used unk).

2024-04-04 13:24 UTC, adambarla commented
could you please remove the debug prints? also do we need to keep the old version of `word.py`?

2024-04-04 13:30 UTC, adambarla requested changes

2024-04-04 13:30 UTC, adambarla commented on src/conf/main.yaml
please don't commit your local changes in the configs or don't change them at all and just use `device="cuda:3"` in the training command

2024-04-04 13:30 UTC, adambarla commented on src/tokenizer/word_old.py
is this file needed?

2024-04-04 13:30 UTC, adambarla commented on src/tokenizer/word.py
> +        print(f"Decoded text: {decoded_text}")
is this print necessary?

2024-04-04 13:30 UTC, adambarla commented on src/tokenizer/word.py
> +        print(f"Unknown token ID: {self.unk_token_id}")
are these prints necessary?

2024-04-04 13:30 UTC, adambarla commented on src/training.py
> +    device = get_device(cfg) #torch.device("cuda:1")
remove this comment please

2024-04-04 13:30 UTC, adambarla commented on src/training.py
> +    #added by me
and this one

2024-04-04 13:38 UTC, DecayingSeart commented on src/training.py
> +    #added by me
Fixed

2024-04-04 13:42 UTC, adambarla approved these changes

2024-04-04 13:42 UTC, merged